// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/utility/AppButton.vue')['default']
    AppCard: typeof import('./components/utility/AppCard.vue')['default']
    AppCaseStudyCard: typeof import('./components/utility/AppCaseStudyCard.vue')['default']
    AppDialog: typeof import('./components/utility/AppDialog.vue')['default']
    AppInput: typeof import('./components/inputs/AppInput.vue')['default']
    AppMultistepContainer: typeof import('./components/utility/AppMultistepContainer.vue')['default']
    AppPhoneInput: typeof import('./components/inputs/AppPhoneInput.vue')['default']
    AppSlider: typeof import('./components/utility/AppSlider.vue')['default']
    AppSpinner: typeof import('./components/utility/AppSpinner.vue')['default']
    AppStepper: typeof import('./components/utility/AppStepper.vue')['default']
    AppToastError: typeof import('./components/toasts/AppToastError.vue')['default']
    AppToastSuccess: typeof import('./components/toasts/AppToastSuccess.vue')['default']
    ClientOnly: typeof import('./components/utility/ClientOnly.vue')['default']
    TheAboutAboutSection: typeof import('./components/sections/about/TheAboutAboutSection.vue')['default']
    TheAboutComponent: typeof import('./components/about/TheAboutComponent.vue')['default']
    TheAboutEmployeesSection: typeof import('./components/sections/about/TheAboutEmployeesSection.vue')['default']
    TheAboutHeroSection: typeof import('./components/sections/about/TheAboutHeroSection.vue')['default']
    TheAboutOperateSection: typeof import('./components/sections/about/TheAboutOperateSection.vue')['default']
    TheAboutPerksSection: typeof import('./components/sections/about/TheAboutPerksSection.vue')['default']
    TheAboutSection: typeof import('./components/sections/index/TheAboutSection.vue')['default']
    TheAboutTimeline: typeof import('./components/sections/about/TheAboutTimeline.vue')['default']
    TheCaseStudySection: typeof import('./components/sections/index/TheCaseStudySection.vue')['default']
    TheCultureAboutSection: typeof import('./components/sections/culture/TheCultureAboutSection.vue')['default']
    TheCultureFaqSections: typeof import('./components/sections/culture/TheCultureFaqSections.vue')['default']
    TheCultureHeroSection: typeof import('./components/sections/culture/TheCultureHeroSection.vue')['default']
    TheCultureOpenRoles: typeof import('./components/sections/culture/TheCultureOpenRoles.vue')['default']
    TheCultureOurServices: typeof import('./components/sections/culture/TheCultureOurServices.vue')['default']
    TheCulturePerksSection: typeof import('./components/sections/culture/TheCulturePerksSection.vue')['default']
    TheCultureSeeOurWork: typeof import('./components/sections/culture/TheCultureSeeOurWork.vue')['default']
    TheExpertiseSection: typeof import('./components/sections/index/TheExpertiseSection.vue')['default']
    TheFaqComponent: typeof import('./components/utility/TheFaqComponent.vue')['default']
    TheFaqSection: typeof import('./components/sections/index/TheFaqSection.vue')['default']
    TheHeroSection: typeof import('./components/sections/index/TheHeroSection.vue')['default']
    TheLayoutFooter: typeof import('./components/layout/TheLayoutFooter.vue')['default']
    TheLayoutNavbar: typeof import('./components/layout/TheLayoutNavbar.vue')['default']
    ThePerkComponent: typeof import('./components/testimonial/ThePerkComponent.vue')['default']
    TheTestimonialComponent: typeof import('./components/testimonial/TheTestimonialComponent.vue')['default']
    TheTestimonialsSection: typeof import('./components/sections/index/TheTestimonialsSection.vue')['default']
    TheWeHelpSection: typeof import('./components/sections/index/TheWeHelpSection.vue')['default']
    TheWorkCaseStudySection: typeof import('./components/sections/work/TheWorkCaseStudySection.vue')['default']
    TheWorkClientsSection: typeof import('./components/sections/work/TheWorkClientsSection.vue')['default']
    TheWorkExploreServicesSection: typeof import('./components/sections/work/TheWorkExploreServicesSection.vue')['default']
    TheWorkFaqSection: typeof import('./components/sections/work/TheWorkFaqSection.vue')['default']
    TheWorkHeroSection: typeof import('./components/sections/work/TheWorkHeroSection.vue')['default']
  }
}
