// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/utility/AppButton.vue')['default']
    AppCard: typeof import('./components/utility/AppCard.vue')['default']
    AppCaseStudyCard: typeof import('./components/utility/AppCaseStudyCard.vue')['default']
    AppCopy: typeof import('./components/AppCopy.vue')['default']
    AppDialog: typeof import('./components/utility/AppDialog.vue')['default']
    AppDialogRegister: typeof import('./components/AppDialogRegister.vue')['default']
    AppDialogSelectDate: typeof import('./components/AppDialogSelectDate.vue')['default']
    AppInput: typeof import('./components/inputs/AppInput.vue')['default']
    AppLink: typeof import('./components/AppLink.vue')['default']
    AppMultistepContainer: typeof import('./components/utility/AppMultistepContainer.vue')['default']
    AppPhoneInput: typeof import('./components/inputs/AppPhoneInput.vue')['default']
    AppSlider: typeof import('./components/utility/AppSlider.vue')['default']
    AppSpinner: typeof import('./components/utility/AppSpinner.vue')['default']
    AppStepper: typeof import('./components/utility/AppStepper.vue')['default']
    AppToastError: typeof import('./components/toasts/AppToastError.vue')['default']
    AppToastSuccess: typeof import('./components/toasts/AppToastSuccess.vue')['default']
    ClientOnly: typeof import('./components/utility/ClientOnly.vue')['default']
    MainSection: typeof import('./components/MainSection.vue')['default']
    TheAboutAboutSection: typeof import('./components/sections/about/TheAboutAboutSection.vue')['default']
    TheAboutComponent: typeof import('./components/about/TheAboutComponent.vue')['default']
    TheAboutHeroSection: typeof import('./components/sections/about/TheAboutHeroSection.vue')['default']
    TheAboutPerksSection: typeof import('./components/sections/about/TheAboutPerksSection.vue')['default']
    TheAboutSection: typeof import('./components/sections/index/TheAboutSection.vue')['default']
    TheCaseStudySection: typeof import('./components/sections/index/TheCaseStudySection.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheDialogRegisterStepComplete: typeof import('./components/TheDialogRegisterStepComplete.vue')['default']
    TheDialogRegisterStepDetails: typeof import('./components/TheDialogRegisterStepDetails.vue')['default']
    TheExpertiseSection: typeof import('./components/sections/index/TheExpertiseSection.vue')['default']
    TheFaqSection: typeof import('./components/sections/index/TheFaqSection.vue')['default']
    TheHeroSection: typeof import('./components/sections/index/TheHeroSection.vue')['default']
    TheHostListItem: typeof import('./components/TheHostListItem.vue')['default']
    TheLayoutFooter: typeof import('./components/layout/TheLayoutFooter.vue')['default']
    TheLayoutNavbar: typeof import('./components/layout/TheLayoutNavbar.vue')['default']
    ThePerkComponent: typeof import('./components/testimonial/ThePerkComponent.vue')['default']
    TheSelectDayItem: typeof import('./components/TheSelectDayItem.vue')['default']
    TheTestimonialComponent: typeof import('./components/testimonial/TheTestimonialComponent.vue')['default']
    TheTestimonialsSection: typeof import('./components/sections/index/TheTestimonialsSection.vue')['default']
    TheWebinarDate: typeof import('./components/TheWebinarDate.vue')['default']
    TheWebinarFooter: typeof import('./components/TheWebinarFooter.vue')['default']
    TheWeHelpSection: typeof import('./components/sections/index/TheWeHelpSection.vue')['default']
  }
}
